### ISSUE TITLE
Init with date value on input messes up format (problem 2)

### ISSUE THREAD

**Issue by kevinmu17** [wakirin/Litepicker#104]
**Describe the bug**
When having 2 inputs with the value filled with a correct date, litepicker rearranges the DD-MM. This is unwanted behaviour.

**To Reproduce**
See codepen down below

**Expected behavior**
Litepicker should leave the format as it's written in the value and not messing it up or rehussle it.

**jsfiddle.net / codepen.io / etc**
https://codepen.io/kevinmu/pen/PoZNXzB (SEE PROBLEM 2)

The weirdest thing is, this happens only with certain values like in the pen now. But when starting the input with dates like 15-07-2020 > 28-07-2020 it is working like it's supposed to. So my gues is that it has something to do with the days + months having a 0 as a starting number.

**Comment by wakirin** [comment]
fixed in v1.4.7

**Comment by scott-fisher-iii** [comment]
I too was seeing this problem and am not anymore after the v1.4.7 update. In fact, @kevinmu17 's CodePen to have the Litepicker version the problem is resolved:
<pre><script src="https://cdn.jsdelivr.net/npm/litepicker@1.4.7/dist/js/main.js"></script></pre> 

I did notice the regular CDN link is still not updated to v1.4.7.
